default_language_version:
  python: python3.9
repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [pre-commit]
    language: system
    entry: isort
    args: [--honor-noqa]
    types: [python]

  - id: flake8
    name: flake8
    stages: [pre-commit]
    language: system
    entry: flake8
    types: [python]

  - id: bandit
    name: bandit
    stages: [pre-commit]
    language: system
    pass_filenames: false
    entry: bandit
    args: [--severity-level, medium, --recursive, src, tests]
    types: [python]