replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

resources: {}

config:
  auth:
    type: "query_param"
  api:
    type: "rest"
    url: "https://my.api.mockaroo.com/offerchannel/client_json.json"

  storage:
    raw:
      account: ""
      container: "raw"
      folder: "api"

  azure:
    clientId: ""
    clientSecret: ""
    subscriptionId: ""
    tenantId: ""
