apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ingest-api.fullname" . }}-job-cleanup
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cleanup
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          kubectl delete job {{ include "ingest-api.fullname" . }}-job --ignore-not-found=true
