{{/* if .Values.job.enabled */}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ingest-files.fullname" . }}-job
  labels:
    {{- include "ingest-files.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "ingest-files.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SOURCE_FOLDER
              value: {{ .Values.config.source.folder | quote }}
            - name: STORAGE_ACCOUNT
              value: {{ .Values.config.storage.raw.account | quote }}
            - name: STORAGE_CONTAINER
              value: {{ .Values.config.storage.raw.container | quote }}
            - name: AZURE_CLIENT_ID
              value: {{ .Values.config.azure.clientId | quote }}
            - name: AZURE_CLIENT_SECRET
              value: {{ .Values.config.azure.clientSecret | quote }}
            - name: AZURE_SUBSCRIPTION_ID
              value: {{ .Values.config.azure.subscriptionId | quote }}
            - name: AZURE_TENANT_ID
              value: {{ .Values.config.azure.tenantId | quote }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{/* end */}}
