api:
  url: "https://my.api.mockaroo.com/offerchannel/client_csv.json"
  key: "8af74270"

storage:
  raw:
    account: "seuarmazem.blob.core.windows.net"
    container: "raw"
    folder: "clients/api"

azure:
  sas_token: "SUA_SAS_TOKEN"

# version
# setup
# pre-commit
# deployment?
# changelog?
# .editorconfig?
