api_url: "https://api.mockaroo.com/api/clients"
api_key: "SUA_CHAVE"
raw_storage_account: "seuarmazem.blob.core.windows.net"
raw_container: "raw"
raw_folder: "clients/api"
azure_sas_token: "SUA_SAS_TOKEN"

# version
# setup
# pre-commit
# deployment?
# changelog?
# .editorconfig?
