default_language_version:
  python: python3.9
repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [pre-commit]
    language: system
    entry: isort
    args: [data-processing/gold/src, --honor-noqa]
    types: [python]
    pass_filenames: false

  - id: flake8
    name: flake8
    stages: [pre-commit]
    language: system
    entry: flake8
    args: [--config=./data-processing/gold/.flake8, data-processing/gold/src]
    types: [python]
    pass_filenames: false

  - id: bandit
    name: bandit
    stages: [pre-commit]
    language: system
    entry: bandit
    args: [--severity-level, medium, --recursive, data-processing/gold/src]
    types: [python]
    pass_filenames: false
