default_language_version:
  python: python3.9
repos:
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [pre-commit]
    language: system
    entry: isort
    args: [--honor-noqa]
    types: [python]
    files: ^data-processing/silver/

  - id: flake8
    name: flake8
    stages: [pre-commit]
    language: system
    entry: flake8
    args: [--config=./data-processing/silver/.flake8]
    types: [python]
    files: ^data-processing/silver/

  - id: bandit
    name: bandit
    stages: [pre-commit]
    language: system
    pass_filenames: false
    entry: bandit
    args: [--severity-level, medium, --recursive, data-processing/silver/src]
    types: [python]
    files: ^data-processing/silver/
