replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}

config:
  db:
    type: "postgresql"
    connString: "postgresql://user:pass@host:port/dbname?sslmode=require"
    query: "SELECT * FROM customers"

  storage:
    raw:
      account: ""
      container: "raw"
      folder: "database"

  azure:
    clientId: ""
    clientSecret: ""
    subscriptionId: ""
    tenantId: ""
