apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-files
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ingest-files
  template:
    metadata:
      labels:
        app: ingest-files
    spec:
      containers:
        - name: ingest-files
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80