name: Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      azure_credentials:
        description: 'Azure Credentials JSON'
        required: false
        type: string
      acr_name:
        description: 'Azure Container Registry Name'
        required: false
        type: string
      aks_name:
        description: 'AKS Cluster Name'
        required: false
        type: string
      resource_group:
        description: 'Azure Resource Group Name'
        required: false
        type: string

jobs:
  setup-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1

      - name: Login to Azure
        run: |
          echo "${{ github.event.inputs.azure_credentials }}" > azure_credentials.json
          az login --service-principal --username $(jq -r '.clientId' azure_credentials.json) --password $(jq -r '.clientSecret' azure_credentials.json) --tenant $(jq -r '.tenantId' azure_credentials.json)

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ github.event.inputs.resource_group }} --name ${{ github.event.inputs.aks_name }} --admin

      - name: Verify kubectl access (using az aks command invoke)
        run: |
          az aks command invoke \
            --resource-group ${{ github.event.inputs.resource_group }} \
            --name ${{ github.event.inputs.aks_name }} \
            --command "kubectl get nodes"

  deploy-to-aks:
    needs: setup-aks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3.sh | bash

      - name: Deploy to AKS with Helm
        run: |
          image_name=$(basename "$service_path")
          helm upgrade --install $image_name "$service_path/helm" \
            --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/$image_name \
            --set image.tag=${{ github.event.inputs.version }} \
            --namespace default \
            --create-namespace

      - name: Verify deployment in AKS (using az aks command invoke)
        run: |
          az aks command invoke \
            --resource-group ${{ github.event.inputs.resource_group }} \
            --name ${{ github.event.inputs.aks_name }} \
            --command "kubectl get deployments -n default"
