name: Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      azure_credentials:
        description: 'Azure Credentials JSON'
        required: false
        type: string
      acr_name:
        description: 'Azure Container Registry Name'
        required: false
        type: string
      aks_name:
        description: 'AKS Cluster Name'
        required: false
        type: string
      resource_group:
        description: 'Azure Resource Group Name'
        required: false
        type: string

jobs:
  setup_aks:
    runs-on: ubuntu-latest
    outputs:
      service_path: ${{ steps.find_path.outputs.service_path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ github.event.inputs.azure_credentials || secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ github.event.inputs.resource_group || secrets.RESOURCE_GROUP }} --name ${{ github.event.inputs.aks_name || secrets.AKS_NAME }} --admin

      - name: Find service path
        id: find_path
        run: |
          path=$(git ls-tree -r HEAD --name-only | grep 'VERSION' | head -n 1 | xargs dirname)
          echo "service_path=$path"
          echo "service_path=$path" >> $GITHUB_OUTPUT  # Define a saída para o próximo job

  deploy_to_aks:
    needs: setup_aks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: 'v3.7.0'

      - name: Deploy to AKS with Helm
        run: |
          service_path="${{ needs.setup_aks.outputs.service_path }}"
          image_name=$(basename "$service_path")
          helm upgrade --install $image_name "$service_path/helm" \
            --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/$image_name \
            --set image.tag=${{ github.event.inputs.version }} \
            --namespace default \
            --create-namespace

      - name: Verify deployment in AKS (using az aks command invoke)
        run: |
          az aks command invoke \
            --resource-group ${{ github.event.inputs.resource_group || secrets.RESOURCE_GROUP }} \
            --name ${{ github.event.inputs.aks_name || secrets.AKS_NAME }} \
            --command "kubectl get deployments -n default"
